language: php
dist: focal
sudo: false

php:
  - 7.4
  - 8.0
  - 8.1

env:
  global:
    - CONSUL_HTTP_ADDR="127.0.0.1:8500"

before_install: phpenv config-add ./tests/php.ini

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - wget "https://releases.hashicorp.com/consul/1.9.3/consul_1.9.3_linux_amd64.zip"
  - unzip consul_1.9.3_linux_amd64.zip -d $HOME/bin
  - chmod +x $HOME/bin/consul
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

script:
  - ./vendor/bin/phpunit -c phpunit.xml
